### ISSUE TITLE
Consistent templating

### ISSUE THREAD

**Issue by onezpp** [mariocraft987/bark-coding#108]
It is counter-productive to copy the same basic HTML file over to every document: using EJS could compile to a static website and will be scalable when server-side functionality is added.

Additionally, there are inline scripts in some files, but external scripts in others: shouldn't all scripts be external for consistency?

**Comment by mariocraft987** [comment]
i've been thinking of doing this

**Comment by mariocraft987** [comment]
possible that would be added

**Comment by qwertyy-dev** [comment]
this is a good idea, it's annoying changing every individual page when there's an update like that

**Comment by dumorando** [comment]
@mariocraft987 i could add this if u want

**Comment by Bashamega** [comment]
@qwertyy-dev Isn't the index.js per form the same function?

**Comment by qwertyy-dev** [comment]
> @qwertyy-dev Isn't the index.js per form the same function?

i'm sorry, i don't understand what you're trying to say

**Comment by Bashamega** [comment]
> > @qwertyy-dev Isn't the index.js per form the same function?
> 
> i'm sorry, i don't understand what you're trying to say

I mean that the index.js has the same functionality

**Comment by Bashamega** [comment]
Hello:)
We already solved this issue
