### ISSUE TITLE
Better emoji json

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#112]
I Want A Feature for bark!

 - Name: mariocraft987

**Feature Info**
This is an eyesore
`.replaceAll(":happy:", "<img src='src/emojis/svg/normal/happy.svg' alt='happy face' style='margin-bottom: -7px;' width='"+ emojisize + "' height='"+ emojisize + "'>")`
So why not put all the emoji data such as alt, URL, and name into a json list instead of having all of that mess in `replacer.js`

**Comment by dumorando** [comment]
added in commit 364bcda

**Comment by mariocraft987** [comment]
Yay
