### ISSUE TITLE
Unessesary censoring

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#113]
Go into `replacer.js` and find a bunch of disgusting profain words that some kid could bump into this.

Solution: Censor only important bad words inless of censoring THE WHOLE BOOK OF THEM + PROFAIN INTERNET WORDS

**Comment by qwertyy-dev** [comment]
everything listed there is either a sex position, generally offensive word, or slang term for something offensive. i say better safe than sorry. when is someone going to say "rusty trombone" in a non-offensive way?!?!?

**Comment by mariocraft987** [comment]
In a way that people won't understand

**Comment by qwertyy-dev** [comment]
also, one other thing, what do you mean "unnecessary"?? they are all offensive, none of it is "unnecessary" (okay maybe one or two, but not the whole thing)

**Comment by qwertyy-dev** [comment]
that's a great idea

**Comment by mariocraft987** [comment]
No profanity seen and still censors

**Comment by BwnnyRxbbit** [comment]
Anyways, you guys are still missing a bunch of bad words. And a fair amount of the words aren't even censored on scratch and I think they should be fine.

Also, how can I be a collaborator? I have a lot of experience in HTML, CSS and JavaScript. Have a look at my repos. I know how to create forks, PRs, issues and all of that.
