### ISSUE TITLE
editor category contrast issues

### ISSUE THREAD

**Issue by qwertyy-dev** [mariocraft987/bark-coding#127]
when i select the logic, loops, text, sine, or custom category menu, i have a hard time reading the text inside
![Screenshot from 2024-05-04 09-38-40](https://github.com/mariocraft987/bark-coding/assets/129226914/31865589-9a48-4781-a173-76485c108246)
![Screenshot from 2024-05-04 09-38-49](https://github.com/mariocraft987/bark-coding/assets/129226914/21f9e5c4-95ff-4f3e-9a7f-d0273567691f)
![Screenshot from 2024-05-04 09-38-57](https://github.com/mariocraft987/bark-coding/assets/129226914/a3573052-7243-4be2-934d-ba3b57240f37)
![Screenshot from 2024-05-04 09-39-06](https://github.com/mariocraft987/bark-coding/assets/129226914/635cdf7a-a380-4ea3-ba32-e144258025ee)
![Screenshot from 2024-05-04 09-39-18](https://github.com/mariocraft987/bark-coding/assets/129226914/444edf1a-23e1-46a0-837a-bda82d6e3581)

**Comment by Rubiidev-18** [comment]
fixed in 17b5d2d

**Comment by mariocraft987** [comment]
It changed from full color to different contrasts for me
