### ISSUE TITLE
Scrollable block category bar

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#132]
I Want A Feature for bark!

 - Name: mariocraft987

**Feature Info**
![Screenshot 2024-05-08 095349](https://github.com/mariocraft987/bark-coding/assets/154646419/c962dca9-6047-4209-8a22-18ddc4cf27fe)
Why not make the category bar scroll? if the blockbar can scroll
![Screenshot 2024-05-08 095151](https://github.com/mariocraft987/bark-coding/assets/154646419/a70fa34c-e632-4e9b-9816-077b7a28be02)
That way, we can have more extensions added!

**Comment by Bashamega** [comment]
Hello Mario:)
I would like to work on this
