### ISSUE TITLE
Dark mode Theme

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark-coding#133]
Hello:)

I think the project is coming together, but it is missing a dark mode theme. I would like to work on that.

**Comment by qwertyy-dev** [comment]
![Screenshot from 2024-05-08 20-49-40](https://github.com/mariocraft987/bark-coding/assets/129226914/8198af91-0a36-434c-a168-6f461a530bcc)

**Comment by Bashamega** [comment]
> the moon button in the navbar toggles dark mode. ![Screenshot from 2024-05-08 20-49-40](https://private-user-images.githubusercontent.com/129226914/329119963-8198af91-0a36-434c-a168-6f461a530bcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjc0MjYsIm5iZiI6MTcxNTIyNzEyNiwicGF0aCI6Ii8xMjkyMjY5MTQvMzI5MTE5OTYzLTgxOThhZjkxLTBhMzYtNDM0Yy1hMTY4LTZmNDYxYTUzMGJjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwMzU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGZmNWIzYTdiMmI2YTA2ZGNmZmU2OTAzMWQ2MzdjNGJjN2Y4ODY4Yzk1NGMzNTIxMTUwMmIwMGM0YThhNTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bBx4YopD4yGwVcliphcFtfC1laInjTjph41MF5SbByA)

i forgot sorry

**Comment by qwertyy-dev** [comment]
> i forgot sorry

all good!
