### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by BwnnyRxbbit** [mariocraft987/bark-coding#137]
### Discussed in https://github.com/mariocraft987/bark-coding/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **BwnnyRxbbit** May  8, 2024</sup>
Planning for a new settings page I'm adding.</div>

**Comment by BwnnyRxbbit** [comment]
So can someone carry on from here?

**Comment by mariocraft987** [comment]
@rubiidev18alt made a html file called `themeselect.html` so I see no prb in adding it!

**Comment by Bashamega** [comment]
I can create a cool looking settings page.

**Comment by mariocraft987** [comment]
Okay, in a separate file

**Comment by BwnnyRxbbit** [comment]
> I can create a cool looking settings page.

Ok, you can complete it. https://bark-coding.vercel.app/settings.html

**Comment by Bashamega** [comment]
> > I can create a cool looking settings page.
> 
> Ok, you can complete it. https://bark-coding.vercel.app/settings.html

Ok

**Comment by Bashamega** [comment]
Should a make a folder so it is /settings not /settings.html? Also do we have a db or just store in localStorage?

**Comment by dumorando** [comment]
localstorage for now
