### ISSUE TITLE
About.html says version is 0.1.6 even tho we are on 0.1.7

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark-coding#142]
I have found a bug!

 - Operating System: android
 - Browser: chrome
 - Browser Version: latest

**Description**
title.

**How to Reproduce**
1. go to about.html in homepage
2. see version is 0.1.6

**Expected Behavior**
the version should be 0.1.7

**Screenshots**
too lazy

**Comment by qwertyy-dev** [comment]
i feel like this doesn't need an issue, you can literally edit it yourself, and it's one singular character

**Comment by rubiidev18alt** [comment]
oh ok

**Comment by mariocraft987** [comment]
That’s not really a bug or an error

**Comment by mariocraft987** [comment]
Just change `package.json`
