### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark-coding#144]
Hello :)
My idea is to create a contributor's page, rather than redirecting the user to the GitHub graphs. I would love to work on this.

**Comment by BwnnyRxbbit** [comment]
We could do something similar to [this](https://scratchaddons.com/credits/)?

**Comment by qwertyy-dev** [comment]
> We could do something similar to [this](https://scratchaddons.com/credits/)?

that would be cool, and i like the little emoji emblems, we should definitely have those 😝

**Comment by Bashamega** [comment]
> We could do something similar to [this](https://scratchaddons.com/credits/)?

Yes

**Comment by qwertyy-dev** [comment]
yeah, totally, make this!! this would be great! :)

**Comment by BwnnyRxbbit** [comment]
My main idea was to credit people for ideas, translations, and all other sub-headings other than just coding.

**Comment by Bashamega** [comment]
> My main idea was to credit people for ideas, translations, and all other sub-headings other than just coding.

no problem, but I will need a Json file that contains a username, PFP, and the emoji

**Comment by qwertyy-dev** [comment]
> > My main idea was to credit people for ideas, translations, and all other sub-headings other than just coding.
> 
> no problem, but I will need a Json file that contains a username, PFP, and the emoji

[you can get username + pfp from github api](https://api.github.com/repositories/740694196/contributors)

**Comment by BwnnyRxbbit** [comment]
However we can do something like [this](https://github.com/ScratchAddons/website-v2/issues/440).

**Comment by Bashamega** [comment]
What about the emoji, how can i generate it from the api?

**Comment by qwertyy-dev** [comment]
> What about the emoji, how can i generate it from the api?

we can make a json for that

**Comment by Bashamega** [comment]
> > What about the emoji, how can i generate it from the api?
> 
> we can make a json for that

This is what i meant.

**Comment by qwertyy-dev** [comment]
> > > What about the emoji, how can i generate it from the api?
> > 
> > 
> > we can make a json for that
> 
> This is what i meant.

oh sorry, i thought you meant getting it from the api, which you can't really do :P
