### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark-coding#147]
Hello:)
I know that it is quite early for the integration of the database. But I would like to start developing the account and profile pages.
I am going to create another branch called profiles, which I will add the version of the bark when the user is logged in and has a profile page.
Can I start working on it?

**Comment by Rubiidev-18** [comment]
yea, sure. but make it localstorage for now, also, post these types of stuff in the discussions in the q&a section next time.
