### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark-coding#149]
If you don't have a theme in your localStorage then the theme won't load.

It is working but @qwertyy-dev  broke it.
So please fix it

**Comment by Bashamega** [comment]
![Screenshot_20240512_013500_Chrome.jpg](https://github.com/mariocraft987/bark-coding/assets/110662505/f3f36c0c-005b-4145-ab5c-d64c13fc1121)

**Comment by qwertyy-dev** [comment]
oops. i'll fix

**Comment by qwertyy-dev** [comment]
fixed :)

**Comment by Bashamega** [comment]
> oops. i'll fix

Thanks
