### ISSUE TITLE
color contrast issues (yes, again 🥲)

### ISSUE THREAD

**Issue by qwertyy-dev** [mariocraft987/bark-coding#153]
when you set the navbar color to a bright color in settings, it doesn't set the text color to black, making it very hard or impossible to read.
![Screenshot from 2024-05-11 17-52-33](https://github.com/mariocraft987/bark-coding/assets/129226914/305af3b6-5023-43fc-b5a2-96d27932e582)

**Comment by BwnnyRxbbit** [comment]
Go to [this](https://bark-coding.vercel.app/settings) page in dark mode and you'll see another issue.

**Comment by qwertyy-dev** [comment]
> Go to [this](https://bark-coding.vercel.app/settings) page in dark mode and you'll see another issue.

indeed, i noticed that too but forgot to make an issue

**Comment by Bashamega** [comment]
I am going to work on it.
