### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark-coding#161]
Hello :)

The nav bar is not responsive.
![Screenshot_20240512_155538_Samsung Internet.jpg](https://github.com/mariocraft987/bark-coding/assets/110662505/6fa64526-3057-418a-8a9f-32ecfbc5c9ee)
I suggest add a hamburger menu

**Comment by mariocraft987** [comment]
Wut…

**Comment by Bashamega** [comment]
> Wut…

The nav bar is not responsive on mobile

**Comment by qwertyy-dev** [comment]
i hate to unironically say this, but... it works on my device. if you mean the buttons clip off the side of the screen, the navbar is scrollable

**Comment by Bashamega** [comment]
> i hate to unironically say this, but... it works on my device. if you mean the buttons clip off the side of the screen, the navbar is scrollable

It is also scrollable, but not many people will try to scroll. And also the sign in button and the Join buttons are cut off
![Screenshot_20240513_054113_Chrome.jpg](https://github.com/mariocraft987/bark-coding/assets/110662505/e772e197-0ad7-4739-90e7-8a474c49d979)

**Comment by qwertyy-dev** [comment]
'tis true. i'll add a notice saying you can scroll?

**Comment by Bashamega** [comment]
> 'tis true. i'll add a notice saying you can scroll?

No I think it will be better if there was a hamburger menu

**Comment by qwertyy-dev** [comment]
i could do that as well. i'll get that done asap

**Comment by Bashamega** [comment]
did you finish it @qwertyy-dev. If you are busy i can finish it

**Comment by qwertyy-dev** [comment]
> did you finish it @qwertyy-dev. If you are busy i can finish it

sorry, i totally forgot about this. can somebody else do it? i'm all wrapped up in my own project right now

**Comment by Bashamega** [comment]
> > did you finish it @qwertyy-dev. If you are busy i can finish it
> 
> sorry, i totally forgot about this. can somebody else do it? i'm all wrapped up in my own project right now

No problem. I can work on it
