### ISSUE TITLE
You can't see the difference between the project and the description.

### ISSUE THREAD

**Issue by BwnnyRxbbit** [mariocraft987/bark-coding#169]
<img width="476" alt="Screenshot 2024-05-14 at 7 15 39 AM" src="https://github.com/mariocraft987/bark-coding/assets/167290033/b75b8d50-010a-436e-b960-ae706cb87284">

**Comment by rubiidev18alt** [comment]
qwertyy can desaturate the background below the editor stage.
 @qwertyy-dev

**Comment by qwertyy-dev** [comment]
um why is it not fixed there's supposed to be a border

**Comment by qwertyy-dev** [comment]
do not close, it is not completed
