### ISSUE TITLE
text is black on settings

### ISSUE THREAD

**Issue by Rubiidev-18** [mariocraft987/bark-coding#170]
image says everything.
![Screenshot_20240514_004940796Quick](https://github.com/mariocraft987/bark-coding/assets/158863401/755b0720-0d6c-4763-801a-3e3133cca312)

**Comment by BwnnyRxbbit** [comment]
I'm not sure how to fix this. @Bashamega was the one that made it.

**Comment by Bashamega** [comment]
> I'm not sure how to fix this. @Bashamega was the one that made it.

I am going to fix it tonight

**Comment by Bashamega** [comment]
I have fixed it

**Comment by BwnnyRxbbit** [comment]
I'm confused. Shouldn't the box be light black and the text be white?

**Comment by Bashamega** [comment]
> I'm confused. Shouldn't the box be light black and the text be white?

I didn't code it to be like that.
If you want I can make it to be like that

**Comment by BwnnyRxbbit** [comment]
> > I'm confused. Shouldn't the box be light black and the text be white?
> 
> I didn't code it to be like that. If you want I can make it to be like that

It just looks weird when there is a big blob of white in dark mode.

**Comment by Bashamega** [comment]
Done @BwnnyRxbbit

**Comment by BwnnyRxbbit** [comment]
> Done @BwnnyRxbbit

Looks good, not being picky but can you make the warnings have a black background with white text?

**Comment by Bashamega** [comment]
> > Done @BwnnyRxbbit
> 
> Looks good, not being picky but can you make the warnings have a black background with white text?

Sure

**Comment by Bashamega** [comment]
It should be better now

**Comment by BwnnyRxbbit** [comment]
> It should be better now

Ok, I made a slight edit to the page. As well. (Now the warning background and box background aren't the same colour (fixed on dark and light mode))
