### ISSUE TITLE
`/contributors/` stylesheet is not local

### ISSUE THREAD

**Issue by qwertyy-dev** [mariocraft987/bark-coding#174]
- Operating System: linux mint cinnamon
 - Browser: google chrome
 - Browser Version: latest version

**Description**
the css on `/contributors/` is behaving on odd ways. the grid is broken and links look goofy

**How to Reproduce**
1. navigated to `/about/`
2. clicked "credits"

**Expected Behavior**
for it to look like it did a day or two ago

**Screenshots**
![Capture](https://github.com/mariocraft987/bark-coding/assets/129226914/19dad385-4752-4fe4-9982-4e434de9a9c3)
![Capture1](https://github.com/mariocraft987/bark-coding/assets/129226914/cab0f816-3ebc-4f3e-b1ae-935f7f0ce9ff)

**Notes**
this may be because the link to the stylesheet is blocked on school computers. if this is the case, i suggest we put the stylesheet in the local repo

**Comment by BwnnyRxbbit** [comment]
It is working for me so I think it may be blocked on your laptop like you mentioned.

**Comment by qwertyy-dev** [comment]
yup. it is. can somebody add the stylesheet locally to prevent this?

**Comment by Bashamega** [comment]
> yup. it is. can somebody add the stylesheet locally to prevent this?

Sure I am going to make it local.

**Comment by Bashamega** [comment]
It should be fixed now @qwertyy-dev
