### ISSUE TITLE
[bug] broken blockbar

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#183]
### Operating System

- [ ] Android
- [ ] ChromeOS
- [ ] iOS
- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other

### Browser(s)

- [ ] Arc
- [X] Chrome
- [ ] Firefox
- [ ] Internet (Galaxy)
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Safari
- [ ] Other

### What happened

Welp, the blockbar broke

### Expected Behavior

For the blocks to line up in order

### Screenshots

![Screenshot 2024-05-22 083418](https://github.com/mariocraft987/bark-coding/assets/154646419/7b90d433-e962-49f8-ab0e-58695e9b08bd)

**Comment by qwertyy-dev** [comment]
this has happened to me in the past. these symptoms indicate that this is because somebody made a block incorrectly

**Comment by mariocraft987** [comment]
F

**Comment by Bashamega** [comment]
Also the styles block is broken.
After some git blame i found that @Rubiidev-18 is the one who created the 2 blocks

**Comment by mariocraft987** [comment]
💀

**Comment by Bashamega** [comment]
> 💀 Can you fix it? I can't find the error he made

ok

**Comment by Bashamega** [comment]
i don't se the issue.

**Comment by Bashamega** [comment]
if we can find the commit maybe you can revert it

**Comment by mariocraft987** [comment]
Fixed in ccb0688
