### ISSUE TITLE
[bug] theme error

### ISSUE THREAD

**Issue by qwertyy-dev** [mariocraft987/bark-coding#187]
### Operating System

- [ ] Android
- [ ] ChromeOS
- [ ] iOS
- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other

### Browser(s)

- [ ] Arc
- [X] Chrome
- [ ] Firefox
- [ ] Internet (Galaxy)
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Safari
- [ ] Other

### What happened

theme is broken

### Expected Behavior

for the theme to show

### Screenshots

![image](https://github.com/mariocraft987/bark-coding/assets/129226914/389fd1c3-ecb7-4521-a56b-39a2ac9a1881)

**Comment by mariocraft987** [comment]
i risked it trying to make a better navbar

**Comment by Bashamega** [comment]
Which theme?
They are all working for me

**Comment by mariocraft987** [comment]
was fixed in commit [7cc59cd](https://github.com/mariocraft987/bark-coding/commit/7cc59cd1abadc5d400d26d685c80e628231e8ef5)
