### ISSUE TITLE
[bug] broken dark mode button

### ISSUE THREAD

**Issue by qwertyy-dev** [mariocraft987/bark-coding#192]
### Operating System

- [x] Android
- [ ] ChromeOS
- [ ] iOS
- [X] Linux
- [x] Mac
- [ ] Windows
- [ ] Other

### Browser(s)

- [ ] Arc
- [x] Chrome
- [X] Firefox
- [ ] Internet (Galaxy)
- [ ] Microsoft Edge
- [ ] Opera
- [x] Safari
- [ ] Other

### What happened

clicking the dark mode button does nothing

### Screenshots

i got this error: `failed to add click event for the dark mode toggle :( TypeError: darkModeToggle is null`

**Comment by qwertyy-dev** [comment]
this can be easily fixed if we just move everything in `navbar.js` back to `index.js`

**Comment by Bashamega** [comment]
I am going to fix this

**Comment by Bashamega** [comment]
I have fixed it, by adding an onclick
