### ISSUE TITLE
[FEAT] Use vercel rewrites instead of folders for each page

### ISSUE THREAD

**Issue by dumorando** [mariocraft987/bark-coding#193]
https://vercel.com/docs/edge-network/rewrites
it would make the source code a bit cleaner
example:
```json
{
  "rewrites": [
    {
      "source": "/credits",
      "destination": "/misc/credits.html"
    }
  ]
}
```
or smth like that idk

**Comment by qwertyy-dev** [comment]
yes can we please do this, all these folders for the website are just too much

**Comment by Bashamega** [comment]
> https://vercel.com/docs/edge-network/rewrites it would make the source code a bit cleaner example:
> 
> ```json
> {
>   "rewrites": [
>     {
>       "source": "/credits",
>       "destination": "/misc/credits.html"
>     }
>   ]
> }
> ```
> 
> or smth like that idk

I can work on that

**Comment by mariocraft987** [comment]
k, on a fork
