### ISSUE TITLE
No languages in the list

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#195]
### Operating System

- [ ] Android
- [ ] ChromeOS
- [ ] iOS
- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other

### Browser(s)

- [ ] Arc
- [X] Chrome
- [x] Firefox
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Safari
- [ ] Other

### What happened

I tried to change the language in `settings.html` but saw NONE, I saw no languages at all

### Expected Behavior

I expected it to be the normal default languages

### Screenshots

![Screenshot 2024-05-25 134044](https://github.com/mariocraft987/bark-coding/assets/154646419/b2481cb3-38fc-42f4-961b-5c72f7773365)

**Comment by qwertyy-dev** [comment]
i'm seeing this as well

**Comment by qwertyy-dev** [comment]
wow, i killed two birds with one stone. fixed in commit `6af5ca0`
