### ISSUE TITLE
[bug] cant switch back to light mode

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark-coding#201]
### Operating System

- [X] Android
- [ ] ChromeOS
- [ ] iOS
- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other

### Browser(s)

- [ ] Arc
- [X] Chrome
- [ ] Firefox
- [ ] Internet (Galaxy)
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Safari
- [ ] Other

### What happened

press the dark/light mode button 2 times

### Expected Behavior

the website goes to dark mode, then back to light

### Screenshots

none but
"failed to add click event for the dark mode toggle :("

**Comment by mariocraft987** [comment]
An issue almost like #197
