### ISSUE TITLE
wtb https://codebark.io?

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#205]
It's free, plus we will be using it temporarly

**Comment by nmsderp** [comment]
its not free

**Comment by nmsderp** [comment]
![image](https://github.com/mariocraft987/bark-coding/assets/130254323/e6486400-3201-433a-b455-e8dfd2653c71)

**Comment by qwertyy-dev** [comment]
> ![image](https://private-user-images.githubusercontent.com/130254323/336628276-e6486400-3201-433a-b455-e8dfd2653c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDQwNDYsIm5iZiI6MTcxNzU0Mzc0NiwicGF0aCI6Ii8xMzAyNTQzMjMvMzM2NjI4Mjc2LWU2NDg2NDAwLTMyMDEtNDMzYS1iNDU1LWU4ZGZkMjY1M2M3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMzI5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTQ2ZGZjMzA4ZTNlYzIzN2Y3M2ZlMjRlN2FjZGFmZDJiODMwZTZjN2RlYTk0NmE5MmRiYjM0MzliMzYyYmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BbLvbkpNc61oocGgQWfTjA59jxxARUtCgjJ46zN9jVI)

> its not free

in fact, it's the most expensive one suggested so far

**Comment by mariocraft987** [comment]
nvm, its a error
