### ISSUE TITLE
[bug] some of the idea text is not showing up

### ISSUE THREAD

**Issue by Rubiidev-IPad** [mariocraft987/bark-coding#210]
### Operating System

- [X] Android
- [ ] ChromeOS
- [X] iOS
- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other

### Browser(s)

- [ ] Arc
- [X] Chrome
- [X] Firefox
- [ ] Internet (Galaxy)
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Safari
- [ ] Other

### What happened

1. go to idea page
2. put in anything
3. wait for idea
4. see it be cut off

### Expected Behavior

all the text is shown, and the page is scrollable

### Screenshots

everyone test it and add you screenshot here

**Comment by dumorando** [comment]
you can scroll............... scroll inside the box wich has the text.

**Comment by dumorando** [comment]
ok now its more obivous you can scroll in it
