### ISSUE TITLE
[bug] Bros not doing anything

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#211]
### Operating System

- [ ] Android
- [ ] ChromeOS
- [ ] iOS
- [x] Linux
- [ ] Mac
- [X] Windows
- [ ] Other

### Browser(s)

- [ ] Arc
- [X] Chrome
- [ ] Firefox
- [ ] Internet (Galaxy)
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Safari
- [ ] Other

### What happened

I went to the idea generator to see what the talk was about but when i tried to click it, it had a SMALL HITBOX

### Expected Behavior

For it to move on to the next slide

### Screenshots

![Screenshot 2024-06-14 110413](https://github.com/mariocraft987/bark-coding/assets/154646419/a420edcd-0904-46bc-8094-e6e8e3eb3f00)

**Comment by dumorando** [comment]
yea that happens when your on a small screen, i noticed it when i went into the network tab, but it needs to be fixed ya
