### ISSUE TITLE
going insane..

### ISSUE THREAD

**Issue by dumorando** [mariocraft987/bark-coding#216]
if you know how to write node.js backend code, **please help out with bark**.<br />
the code is genuinely so bad to the point where it crashes every 10 minutes making the api a lot slower<br />
![image](https://github.com/mariocraft987/bark-coding/assets/144301348/0849d3cb-4578-48c1-997d-35f1e88dcfba)
not only that, the entire database is contained in a json replit.db key, which results in the server only allowing 1 operation at a time to prevent data overwriting, which again, makes the api a lot slower.<br />
if anyone knows a better database solution, and nodejs, please tell me your replit account.<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

and i **do NOT** want your chatgpt code!!!!

**Comment by dumorando** [comment]
code: https://replit.com/@dumorando/bark-api?v=1

**Comment by nmsderp** [comment]
it may work better with [easyjsondatabase](https://www.npmjs.com/package/easy-json-database), which is used in the Snail IDE server

**Comment by dumorando** [comment]
easyjsondatabase would be great but im hosting this on replit which doesnt have persistent storage

**Comment by nmsderp** [comment]
> easyjsondatabase would be great but im hosting this on replit which doesnt have persistent storage

this seems good, you get 3gb of storage, 2gb ram, and 1.25 cpu cores, for completely free https://sillydev.co.uk/

**Comment by dumorando** [comment]
> > easyjsondatabase would be great but im hosting this on replit which doesnt have persistent storage
> 
> this seems good, you get 3gb of storage, 2gb ram, and 1.25 cpu cores, for completely free https://sillydev.co.uk/

i'll check it out

**Comment by dumorando** [comment]
> > easyjsondatabase would be great but im hosting this on replit which doesnt have persistent storage
> 
> this seems good, you get 3gb of storage, 2gb ram, and 1.25 cpu cores, for completely free https://sillydev.co.uk/

it only lets you have 512mb of storage,.

**Comment by nmsderp** [comment]
huh 
![image](https://github.com/mariocraft987/bark-coding/assets/130254323/39ab05cc-93dc-44ac-9f57-901162b8953d)

**Comment by Bashamega** [comment]
Please check your discord @dumorando
