### ISSUE TITLE
[bug] need new api key for idea generator

### ISSUE THREAD

**Issue by Rubiidev-IPad** [mariocraft987/bark-coding#226]
### Operating System

- [ ] Android/ChromeOS
- [X] iOS
- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other

### Browser(s)

- [ ] Arc
- [X] Chrome
- [ ] Firefox
- [ ] Internet (Galaxy)
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave
- [ ] Safari
- [ ] Other

### What happened

1. try to generate an idea
2. it forever loads

### Expected Behavior

the idea to generate

**Comment by nmsderp** [comment]
i think mubilop blocked the api via cors 
![image](https://github.com/mariocraft987/bark-coding/assets/130254323/dcd755b4-0a73-4dd6-870e-412c8d464d39)

**Comment by breakfast-for-dinner** [comment]
why is it an api what

**Comment by dumorando** [comment]
> i think mubilop blocked the api via cors ![image](https://private-user-images.githubusercontent.com/130254323/344009967-dcd755b4-0a73-4dd6-870e-412c8d464d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDkwMjUsIm5iZiI6MTcxOTU0ODcyNSwicGF0aCI6Ii8xMzAyNTQzMjMvMzQ0MDA5OTY3LWRjZDc1NWI0LTBhNzMtNGRkNi04NzBlLTQxMmM4ZDQ2NGQzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQwNDI1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzE3YjFiOWJkOGJiZjM0NjM5NDllMjJmNzkxNWQ4ZDFhZWNiYWM5MjE3MWZmZTBkMzczZTgxYWY2NWE1ZmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GjOhAnfDRpT9Qjou6U0V1AyFlBylnZH-tw09Nh0aK60)

lmfao

**Comment by dumorando** [comment]
not possible
