### ISSUE TITLE
@rubiidev18alt: nms pls port the snail ide theme for the new theme

### ISSUE THREAD

**Issue by breakfast-for-dinner** [mariocraft987/bark-coding#228]
### Discussed in https://github.com/mariocraft987/bark-coding/discussions/227

<div type='discussions-op-text'>

<sup>Originally posted by **rubiidev18alt** June 27, 2024</sup>
@nmsderp</div>

**Comment by dumorando** [comment]
thats quite the large command

**Comment by dumorando** [comment]
btw y cant u do it

**Comment by nmsderp** [comment]
what is this supposed to mean?

**Comment by breakfast-for-dinner** [comment]
> what is this supposed to mean?

i don't know, but it might have been done already in [`e40b5d1`](https://github.com/mariocraft987/bark-coding/commit/e40b5d1493e646af5deb2a8af724a5118e36f8d0?diff=unified&w=1)

**Comment by nmsderp** [comment]
> > what is this supposed to mean?
> 
> i don't know, but it might have been done already in [`e40b5d1`](https://github.com/mariocraft987/bark-coding/commit/e40b5d1493e646af5deb2a8af724a5118e36f8d0?diff=unified&w=1)

close i guess
