### ISSUE TITLE
make `Rubii484bark` and `nmsderp` bark accounts official team accounts

### ISSUE THREAD

**Issue by breakfast-for-dinner** [mariocraft987/bark-coding#240]

**Comment by breakfast-for-dinner** [comment]
> Hello! 👋 Thanks for opening this issue. We appreciate your feedback and will look into it as soon as possible. Feel free to add more details if necessary.

why does this exist

**Comment by dumorando** [comment]
idk bashamega added it cause its professional or smt

**Comment by dumorando** [comment]
discuss all officially hosted issues at https://github.com/dumorando/bapiv2/discussions please
