### ISSUE TITLE
[FEAT] URL link protection

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark-coding#241]
**Is your feature request related to a problem? Please describe.**
I am thinking of making it so that if the url link to outside of the site it will go to a page to make sure that the user want to visit that website
**Describe the solution you'd like**
I would modify the `replace.js` to make it link to an inside page that will ask the user if he wants to go there

**Comment by mariocraft987** [comment]
From what I see of your problem, is that you can do `prompt()` to confirm if the user wants to go there?

**Comment by Bashamega** [comment]
> From what I see of your problem, is that you can do `prompt()` to confirm if the user wants to go there?

It won't be good ui to use prompt. I was going to make a specific page for it. 
I can create it. If you like the general idea.

**Comment by mariocraft987** [comment]
sorry, i forgot to replace `prompt()` with `confirm()`

**Comment by Bashamega** [comment]
> sorry, i forgot to replace `prompt()` with `confirm()`

I won't be using them
