### ISSUE TITLE
Donate using repl cycles

### ISSUE THREAD

**Issue by Rubiidev-18** [mariocraft987/bark-coding#25]
**https://docs.replit.com/cycles/about-cycles**
You could make a replit project called smth like "Bark cycles" which you can use for donating

**Comment by mariocraft987** [comment]
Maybe..

**Comment by nmsderp** [comment]
i mean yeah, @thepython555 has to pay like 100 bucks for repl.it core, and cycles would help

**Comment by qwertyytheartist** [comment]
who's gonna make the donation thing?

**Comment by qwertyytheartist** [comment]
when somebody makes this i will donate asap

**Comment by Rubiidev-18** [comment]
> who's gonna make the donation thing?

mariocraft (the owner) def will make it himself

> when somebody makes this i will donate asap

👍 (we need the bark style emojis for this github)

**Comment by qwertyytheartist** [comment]
> 👍 (we need the bark style emojis for this github)

lol. wait, is there a way to do that??

**Comment by Rubiidev-18** [comment]
> > 👍 (we need the bark style emojis for this github)
> 
> lol. wait, is there a way to do that??

you need to install a userscript, but you can use
https://github.com/StylishThemes/GitHub-Custom-Emojis/blob/master/README.md

**Comment by qwertyytheartist** [comment]
> > > 👍 (we need the bark style emojis for this github)
> > 
> > 
> > lol. wait, is there a way to do that??
> 
> you need to install a userscript, but you can use https://github.com/StylishThemes/GitHub-Custom-Emojis/blob/master/README.md

bummer. chrome won't let me install 🙄

**Comment by Rubiidev-18** [comment]
> > > > 👍 (we need the bark style emojis for this github)
> > > 
> > > 
> > > lol. wait, is there a way to do that??
> > 
> > 
> > you need to install a userscript, but you can use https://github.com/StylishThemes/GitHub-Custom-Emojis/blob/master/README.md
> 
> bummer. chrome won't let me install 🙄

try firefox_librewolf

**Comment by thepython555** [comment]
But i didnt even create the server yet :trollface:

**Comment by mariocraft987** [comment]
:trollface: Hehe

**Comment by nmsderp** [comment]
i just realized repl.it is non-ephemeral meaning all of the projects would only be stored for like a couple seconds, would be better to use something else

**Comment by thepython555** [comment]
> i just realized repl.it is non-ephemeral meaning all of the projects would only be stored for like a couple seconds, would be better to use something else

i can use replit.db

**Comment by nmsderp** [comment]
> > i just realized repl.it is non-ephemeral meaning all of the projects would only be stored for like a couple seconds, would be better to use something else
> 
> i can use replit.db

i forgor about that

**Comment by thepython555** [comment]
yeah i wanted to port penguinmod api to it but it would be too hard

**Comment by thepython555** [comment]
bark should be easy tho

**Comment by onezpp** [comment]
just get a vps

**Comment by mariocraft987** [comment]
"vps"?

**Comment by nmsderp** [comment]
> "vps"?

its basically a cloud virtual machine https://cloud.google.com/learn/what-is-a-virtual-private-server

**Comment by nmsderp** [comment]
but they do cost like 300$

**Comment by mariocraft987** [comment]
🫗💰

**Comment by dumorando** [comment]
i'm not gonna host the server on replit

**Comment by dumorando** [comment]
nvm i could, replit buckets dropped

**Comment by dumorando** [comment]
> just get a vps

those are wayy to expensive

**Comment by dumorando** [comment]
the backend is finished at https://bark-backend-prod.replit.app i think so uhh ima add it to the gui tmr
