### ISSUE TITLE
get rid of block editor entirely it's too much pain

### ISSUE THREAD

**Issue by sillybreakfast** [mariocraft987/bark-coding#260]
**Is your feature request related to a problem? Please describe.**
the block editor still doesn't function after 8 months of development

**Describe the solution you'd like**
originally nmsderp's idea, i suggest we get rid of the block editor entirely and stick to the advanced editor.

**Describe alternatives you've considered**
- rewriting the block editor from scratch (agony)
- learning blockly (agony)

**Additional context**
none

**Comment by mariocraft987** [comment]
Yes, could be a lot better and less scope

**Comment by nmsderp** [comment]
heavily agree

**Comment by mariocraft987** [comment]
done in 6df3de7
