### ISSUE TITLE
explore page has no use rn

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#265]
should we just remove it?

what should we add to it.

**Comment by Rubiidev-IPad** [comment]
when the server is done, a projects gallery, keep the easter egg lol, categories, basically the scratch explor page

**Comment by mariocraft987** [comment]
ok

**Comment by sillybreakfast** [comment]
@dumorando is it possible to add projects to BAPI anytime soon? in the form of a javascript file (so advanced editor only) until we figure out exactly what to do with the block editor.

**Comment by mariocraft987** [comment]
bluds (dumo) gonna get a lot of mentions

**Comment by dumorando** [comment]
> blud

su

> @dumorando is it possible to add projects to BAPI anytime soon?

projects are already added to that api

**Comment by mariocraft987** [comment]
imma have to use 100% of my brainpower

**Comment by sillybreakfast** [comment]
> projects are already added to that api

oh....then..can you explain how to make uploading available from the website?
