### ISSUE TITLE
Sine Wave Bug

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark-coding#67]
I have found a bug!

 - Operating System: Android 14
 - Browser: Chrome

**Description**
while I was messing with the sine wave y block (this might also happen with x) when I was spamming the run button, the sine wave speeded up! (also I deleted the block from the scripts panel and the sine is still going, so maybe fix that too.)

**How to Reproduce**
1. go into the editor
2. drag in a sine wave x or y block
3. spam the run button

**Expected Behavior**
the sine wave stays at the same speed, even when you click the run button multiple times

**Screenshots**

https://github.com/mariocraft987/bark.github.io/assets/164731988/3efc50c3-4c08-4ace-9ee6-c548495f676d

**Comment by mariocraft987** [comment]
SONIC SPEED

**Comment by nmsderp** [comment]
its cuz we don't have a stop button yet

**Comment by nmsderp** [comment]
fixed
