### ISSUE TITLE
incolorful blockbar

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark-coding#86]
Is this a error or what?
**old blockbar**
![Screenshot 2024-04-03 142427](https://github.com/mariocraft987/bark.github.io/assets/154646419/505f27ef-acbf-4df4-8ecb-2f47bb02e374)
**new blockbar**
![Screenshot 2024-04-03 142420](https://github.com/mariocraft987/bark.github.io/assets/154646419/0fd914cc-e7c3-44a1-8b7c-244456ead788)

**Comment by qwertyy-dev** [comment]
i think it's for style, if you click them the color shows across the whole thing. looks pretty cool, in my opinion

**Comment by mariocraft987** [comment]
oh

**Comment by rubiidev18alt** [comment]
not related to this, but, where did you get the og block bar?

**Comment by mariocraft987** [comment]
Meow
