### ISSUE TITLE
Filter MUST Be Server Side

### ISSUE THREAD

**Issue by nmsderp** [mariocraft987/bark-coding#89]
when project sharing is added, it will be very easy for anyone to who knows how to delete a file to delete replacer.js, when the server is made it NEEDS to be server sided so no one can hack it

**Comment by nmsderp** [comment]
like they could fork it or clone it to their pc and just delete the file

**Comment by mariocraft987** [comment]
dang

**Comment by qwertyy-dev** [comment]
i noticed this to but didn't create an issue because we don't have a server yet

**Comment by nmsderp** [comment]
> i noticed this to but didn't create an issue because we don't have a server yet

i just made this as a heads up

**Comment by mariocraft987** [comment]
maybe a separate repo for scripts

**Comment by qwertyy-dev** [comment]
> maybe a separate repo for scripts

mayhaps
